### ISSUE TITLE
Windows instructions for new device don't currently work

### ISSUE THREAD

**Issue by zwalchuk** [resin-os/resin-edison#109]
The Windows instructions for the Edison ask the user to download the Windows drivers for Edison, but the link is broken, and I could not find another source for the drivers. Does it make sense to change the directions to use the Flash Lite tool? It might be possible to unify these instructions across Windows, Mac, and Linux if that tool works across the board

**Comment by floion** [comment]
I have never used the Edison on Windows. These instructions were here long before I started on the Edison. Maybe @agherzan or @telphan remember about these?

**Comment by floion** [comment]
@zwalchuk this link should be good:

https://downloadmirror.intel.com/26993/eng/IntelEdisonDriverSetup1.2.1.exe
