### ISSUE TITLE
modemManager tries to probe the serial console

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-edison#84]
Currently modemManager tries to probe the edison serial console over and over, this causes noise on the serial console and makes it difficult to work with .dev images.

We probably need to add some udev rule for modemManager to blacklist the edison serial

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_29gd)

**Comment by przemekgalazka** [comment]
any plan for resolving that?

**Comment by floion** [comment]
This item is not very high in the priority list. Is it impacting something in production?

**Comment by przemekgalazka** [comment]
Not really :) .. just asking :)

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-edison/pull/103

**Comment by thgreasi** [comment]
@floion Shouldn't this be closed after v2.7.8+rev3 reaches prod?
(Was on support and saw a thread popping up.)

**Comment by floion** [comment]
This will reach production then, yes. I always prefer to close issues as soon as they get merged, not when we release to resin.io because other people may be building on their own and not use resin.io at all
