### ISSUE TITLE
[kernel 4.13] i2c doesn't appear in /dev and can't be modprobed

### ISSUE THREAD

**Issue by shaunmulligan** [resin-os/resin-edison#98]
When trying to modprobe i2c I get the following:
```
root@1118520:~# modprobe i2c-dev
modprobe: FATAL: Module i2c-dev not found.
```

**Comment by floion** [comment]
@shaunmulligan can you test on version 2.7.8+rev1 please?

**Comment by shaunmulligan** [comment]
@floion is it in staging or should I get from Jenkins?

**Comment by floion** [comment]
@shaunmulligan should be in staging. Will ping you again when sure

**Comment by floion** [comment]
@shaunmulligan you can take it from staging now

**Comment by shaunmulligan** [comment]
@floion I confirm that i2c works on resinOS 2.7.8

**Comment by floion** [comment]
Closing item based on Shaun's confirmation
